APPLICATION = test-ds18
BOARD ?= lora3a-h10

BASE ?= $(CURDIR)/..
RIOTBASE ?= $(BASE)/RIOT
LORA3ABASE ?= $(BASE)/lora3a-boards
PORT ?= /dev/ttyUSB0

EXTERNAL_BOARD_DIRS=$(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS=$(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS=$(LORA3ABASE)/pkg

QUIET ?= 1
DEVELHELP ?= 1

USEMODULE += ds18
USEMODULE += xtimer
USEMODULE += printf_float

CFLAGS += -DDS18_PWR_PIN=GPIO_PIN\(PA,28\) -DDS18_PARAM_PIN=GPIO_PIN\(PB,22\) -DDS18_PARAM_PULL=GPIO_OD_PU

include $(RIOTBASE)/Makefile.include
